services:
  service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: bnb-client
    container_name: bnb-client
    restart: always
    ports:
      - "18080:3000" # 외부포트 : 내부 앱실행 포트       
