services:
  service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: bnb-client
    container_name: bnb-client
    restart: always
    ports:
      - "9000:9000" # 외부포트 : 내부 앱실행 포트
    volumes:
      - /home/ubuntu/apps/uploadData:/upload
